### PR TITLE
Create .ruff.toml

### PR DESCRIPTION
**Pull request by godzail**
remove ruff from pyproject.toml

### CODE REVIEW

**Comment by JeyDi** [comment]
Ciao @godzail thank you for the changes, did you tested if it's working with the python code? Is still valid this configuration?

**Review by JeyDi — COMMENTED** [review]
Can you please update also the same .ruff config into the cookiecutter template and not only in the external config?

**Comment by godzail** [comment]
> Ciao @godzail thank you for the changes, did you tested if it's working with the python code? Is still valid this configuration?

I tried on my project and copy the conf. I did not test on Bear.

**Comment by godzail** [comment]
> Can you please update also the same .ruff config into the cookiecutter template and not only in the external config?

I'll check how to do it.. cookiecutter? maybe a good substitute is copier..

**Pull request merged**
